import { doc } from "firebase/firestore";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { useFirestore, useFirestoreDocData } from "reactfire";

export default function Home() {
  const [allowAudio, setAllowAudio] = useState(false);
  const db = useFirestore();

  const dbRef = doc(db, "audio/settings");
  const { status, data } = useFirestoreDocData(dbRef);
  useEffect(() => {
    if (!audioRef.current || status !== "success") return;
    if (allowAudio) {
      if (data.play) {
        audioRef.current.currentTime = 0;
        void audioRef.current.play();
      } else {
        audioRef.current.pause();
        audioRef.current.currentTime = 0;
      }
    } else {
      audioRef.current.pause();
      audioRef.current.currentTime = 0;
    }
  }, [allowAudio, data, status]);

  const audioRef = useRef<HTMLAudioElement>(null);

  return status === "success" ? (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <audio loop ref={audioRef} className="hidden">
        <source src="/fanfare.mp3" type="audio/mp3" />
      </audio>
      <main className="flex min-h-screen w-full flex-col items-center justify-center bg-[url('/BG_MOBILE.jpg')] bg-cover bg-center">
        <div className="flex w-full max-w-[300px] flex-col gap-2 rounded-md bg-white p-2">
          <p className="w-full text-center font-[Arial] text-base text-black">
            Allow audio?
          </p>
          <div className="flex w-full flex-col gap-1 p-2 font-[Arial]">
            <button
              onClick={() => setAllowAudio(true)}
              className={`${allowAudio ? "bg-green-400" : "bg-white"} w-full rounded-md border border-green-400 py-2`}
            >
              Allow
            </button>
            <button
              onClick={() => setAllowAudio(false)}
              className={`${!allowAudio ? "bg-red-400" : "bg-white"} w-full rounded-md border border-red-400 py-2`}
            >
              Do not Allow
            </button>
          </div>
        </div>
      </main>
    </>
  ) : null;
}
